### PR TITLE
[ci] Run tests against Kibana build from any source branch

### PR DESCRIPTION
**Pull request by dmlemeshko**
## Summary

Updates Jenkins pipeline in order to run custom script from Kibana repo: elastic/kibana/pull/88409
### Checklist

Delete any items that are not applicable to this PR.

- [x] Branch is successfully tested on [Kibana CI](https://kibana-ci.elastic.co/job/elastic+kibana+load-testing/)
- [x] Unit tests are added

### CODE REVIEW

**Review by wayneseymour — CHANGES_REQUESTED** [review]
Should the pipeline logic in .ci/Jenkinsfile live elsewhere?

**Comment by dmlemeshko** [comment]
>Should the pipeline logic in .ci/Jenkinsfile live elsewhere?

I was thinking about it, but creating groovy file is too much for a few lines. I can `sh` command code in separate bash files if it will help. Still Jenkins file is below 100 lines. @LeeDr any thoughts on it?

**Review by LeeDr — APPROVED** [review]
I pulled this PR and ran it against Kibana master and it completed successfully.
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:16 min
[INFO] Finished at: 2021-01-19T12:31:04-06:00
[INFO] ------------------------------------------------------------------------
```


I didn't run a Jenkins job since Dima already did that.

**Review by wayneseymour — APPROVED** [review]
LGTM.  An .editorconfig file might be useful though :)

**Pull request merged**
